### ISSUE TITLE
HASSIO Core update 2023.5.0 broke this i think.

### ISSUE THREAD

**Issue by Aipoc76** [finity69x2/toggle-control-button-row#5]
Updating to HA Core 2023.5.0 broke every one of my control buttons.  If i recall it said that the type did not exist.  Ive since done a roll back.  Brought it up on HASSIO upgrade page, and they said to report it here.

**Comment by cinghialino** [comment]
same problem here

**Comment by Kingo71** [comment]
same here.
Removed and re download, no luck!

**Comment by alesoft73** [comment]
The problem is here 
https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

Polymer Libraray is removed... :-(

**Comment by riksarchen** [comment]
Will this be updated? Miss this in my cards

**Comment by finity69x2** [comment]
I'm working on it...please be patient.

the polymer deprecation caught me off guard with such little notice and I have to figure out how to update it.

**Comment by Aipoc76** [comment]
Awesome. Thank you.

**Comment by riksarchen** [comment]
Fantastic! Thanks a LOT

**Comment by thrasher204** [comment]
3.0 updated is working for me thank you dev!

**Comment by Aipoc76** [comment]
Working great. Thank you

**Comment by finity69x2** [comment]
It should be fixed now.

**Comment by viktak** [comment]
This is still an issue for me. On HA 2023.5.3, with 3.1 version of this control I still get this error in the logs:
```
Logger: frontend.js.latest.202305033
Source: components/system_log/__init__.py:257
First occurred: 12:39:45 PM (3 occurrences)
Last logged: 12:42:17 PM

http://192.168.1.99:8123/hacsfiles/toggle-control-button-row/toggle-control-button-row.js:9:31 Uncaught ReferenceError: Polymer is not defined
```
I have already tried refreshing, removing/reinstalling this component, but I always get the same result.

**Comment by Aipoc76** [comment]
if its still saying " Polymer is not defined" then your not updated...  Ide uninstall and reinstall the module.

**Comment by viktak** [comment]
That's what I thought, but I already unsinstalled it (via HACS) and re-installed it (via HACS) and I still seem to have the old version. I even restarted HA after each removal/install.
Anyway, thanks for confirming this - I'll keep trying...

**Comment by viktak** [comment]
Is it possible that the version in HACS is not updated yet?

**Comment by Aipoc76** [comment]
![image](https://github.com/finity69x2/toggle-control-button-row/assets/42475106/f925951e-dcd1-4212-a55b-c30cf420e15d)
 my HACS is correct..  remember there are 2 cards to update.

**Comment by Aipoc76** [comment]
![image](https://github.com/finity69x2/toggle-control-button-row/assets/42475106/c67c9499-7285-4d78-a51d-fdb8d579466d)
is the other card.

**Comment by viktak** [comment]
I have never used the `Cover Control Button Row` card. So I don't think that is the problem here. However, I installed that too (from HACS), and, as I expected, didn't make any difference.
So far the only way I can get it to work is to not use HACS.
